apiVersion: v1
kind: Service
metadata: 
  name: httpd-svc
  namespace: cgv
  labels:
    app: httpd
spec:
  type: NodePort
  selector:
    owner: cgv
  ports:
  - name: "app-http-port"
    protocol: TCP
    port: 80
    nodePort: 32000
